CREATE DATABASE IF NOT EXISTS api
USE api

CREATE TABLE user (
  id INT  UNSIGNED  NOT NULL AUTO_INCREMENT,
  name VARCHAR(63) NOT NULL,
  email VARCHAR(127) NOT NULL,
  password VARCHAR(127) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  role ENUM('user', 'admin') NOT NULL,
  PRIMARY KEY (id));